services:
  codeoptimizer.api:
    image: ${DOCKER_REGISTRY-}codeoptimizerapi
    build:
      context: .
      dockerfile: CodeOptimizer/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080    
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://codeoptimizer.dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "8080:8080"
    networks:
      - otel

  codeoptimizer.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
      - "18888:18888"
    networks:
      - otel

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - otel

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
    networks:
      - otel

networks:
  otel:
